import { afterEach, expect, it } from 'vitest';
import { mkdir, mkdtemp } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { GenerationStore } from './store.js';
import { FixtureCatalog } from './fixtures.js';
import { GenerationApiService } from './service.js';
import { GenerationWorker } from './worker.js';
import { ProviderOperationError, type GenerationProvider } from './provider/port.js';
import { B21C_REQUEST } from '../../domain/src/authorized-agnes.js';
const opened: GenerationStore[] = [];
afterEach(async () => {
    for (const s of opened.splice(0))
        await s.close();
});
async function setup(provider: GenerationProvider, video = false) {
    await mkdir(resolve('.cache/generation-tests'), { recursive: true });
    const dir = await mkdtemp(resolve('.cache/generation-tests/provider-worker-'));
    const store = await GenerationStore.open(join(dir, 'state'));
    opened.push(store);
    const fixtures = await FixtureCatalog.open(resolve('apps/web/public/demo'));
    let now = 1000;
    const service = new GenerationApiService(store, fixtures, () => now);
    await service.create(video ? { mode: 'video', prompt: '真实编排模拟', references: [], count: 1, video: { durationSeconds: 5, ratio: '16:9', resolution: '720p', audio: false } } : { mode: 'copy', prompt: '真实编排模拟', references: [], count: 1, copy: { language: 'zh-CN', maxCharacters: 200 } }, 'new');
    const worker = new GenerationWorker(store, provider, fixtures, undefined, () => now);
    return { dir, store, fixtures, service, worker, advance: () => { now += 101; }, clock: () => now };
}
it('retains a valid accepted job if private reported facts are malformed', async () => {
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => ({ externalJobId: 'recoverable-job', status: 'queued', reported: { status: 'queued', seconds: -1 } }), get: async () => ({ status: 'unknown' }), download: async () => { throw Error('unexpected'); } };
    const s = await setup(provider); s.advance(); await s.worker.tick();
    expect(s.store.read().attempts[0]).toMatchObject({ externalJobId: 'recoverable-job', submissionState: 'needs_reconciliation' });
    expect(s.store.read().attempts[0]).not.toHaveProperty('reported');
});
it.each(['text', 'fixture', 'provenance'] as const)('rejects real %s outputs before publishing any media', async kind => {
    const fixtures = await FixtureCatalog.open(resolve('apps/web/public/demo'));
    const fixture = await fixtures.readFixture('video-5-16x9-720p-silent');
    const provider: GenerationProvider = { bindingId: 'agnes-authorized-real', create: async () => ({ externalJobId: 'one-job', status: 'queued' }), get: async () => ({ status: 'result_ready', result: { kind: 'https', url: 'https://platform-outputs.agnes-ai.space/synthetic.mp4' } }), download: async () => kind === 'text' ? { kind: 'text', text: 'invalid real video' } : { kind: 'media', bytes: fixture.bytes, sha256: fixture.media.sha256, mime: 'video/mp4', provenance: kind === 'provenance' ? 'synthetic_provider_simulation' : 'real_provider_output', ...(kind === 'fixture' ? { fixtureMedia: fixture.media } : {}) } };
    await mkdir(resolve('.cache/generation-tests'), { recursive: true });
    const dir = await mkdtemp(resolve('.cache/generation-tests/real-invalid-'));
    const store = await GenerationStore.open(join(dir, 'state')); opened.push(store);
    let now = 1000; const service = new GenerationApiService(store, fixtures, () => now);
    expect((await service.create(structuredClone(B21C_REQUEST), 'one')).ok).toBe(true);
    const worker = new GenerationWorker(store, provider, fixtures, undefined, () => now);
    now += 101; await worker.tick(); now += 101; await worker.tick();
    expect(store.read().items[0]).toMatchObject({ status: 'finalizing', errorCode: 'MEDIA_UNAVAILABLE', reviewState: 'pending', libraryState: 'not_saved' });
    expect(store.read().attempts[0]).not.toHaveProperty('rawMedia'); expect(store.read().mediaMetadata).toEqual([]);
});
it('durable ambiguous create never repeats across ticks or reopening and retains reserve without secret', async () => {
    let creates = 0;
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { creates++; throw Error('sentinel-secret-url'); }, get: async () => { throw Error('unexpected GET'); }, download: async () => { throw Error('unexpected download'); } };
    const s = await setup(provider);
    s.advance();
    await s.worker.tick();
    s.advance();
    await s.worker.tick();
    expect(creates).toBe(1);
    expect(s.store.read().items[0]?.status).toBe('needs_reconciliation');
    expect(s.store.read().credits.reserved).toBe(1);
    expect(JSON.stringify(s.store.read())).not.toContain('sentinel-secret-url');
    await s.store.close();
    const reopened = await GenerationStore.open(join(s.dir, 'state'));
    opened.push(reopened);
    await new GenerationWorker(reopened, provider, s.fixtures, undefined, s.clock).tick();
    expect(creates).toBe(1);
});
it('two workers coalesce a persisted claim and retain accepted id when cancel changes version', async () => {
    let creates = 0;
    let release!: () => void;
    let arrived!: () => void;
    const entered = new Promise<void>(r => { arrived = r; });
    const gate = new Promise<void>(r => { release = r; });
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { creates++; arrived(); await gate; return { externalJobId: 'accepted-job', status: 'queued' }; }, get: async () => ({ status: 'failed' }), download: async () => { throw Error('unexpected download'); } };
    const s = await setup(provider);
    s.advance();
    const first = s.worker.tick();
    await entered;
    expect(s.store.read().attempts[0]?.submissionState).toBe('submitting');
    const second = new GenerationWorker(s.store, provider, s.fixtures, undefined, s.clock).tick();
    const item = s.store.read().items[0]!;
    await s.service.cancel(item.id, { expectedVersion: item.version }, 'cancel');
    release();
    await Promise.all([first, second]);
    expect(creates).toBe(1);
    expect(s.store.read().attempts[0]?.externalJobId).toBe('accepted-job');
    expect(s.store.read().items[0]?.status).toBe('cancel_requested');
    s.advance();
    await s.worker.tick();
    expect(s.store.read().items[0]?.status).toBe('failed');
    expect(s.store.read().credits.reserved).toBe(0);
});
it('known pre-send rejection releases and user retry creates new lineage', async () => {
    let creates = 0;
    const provider: GenerationProvider = { bindingId: 'agnes-disabled', create: async () => { creates++; throw new ProviderOperationError('REAL_PROVIDER_CREATE_DISABLED', 'invalid_request', 'not_submitted'); }, get: async () => ({ status: 'unknown' }), download: async () => { throw Error('unexpected'); } };
    const s = await setup(provider);
    s.advance();
    await s.worker.tick();
    const item = s.store.read().items[0]!;
    expect(item.status).toBe('failed');
    expect(s.store.read().credits.reserved).toBe(0);
    const retried = await s.service.retry(item.id, { expectedVersion: item.version }, 'retry');
    expect(retried.ok).toBe(true);
    s.advance();
    await s.worker.tick();
    expect(creates).toBe(2);
    expect(s.store.read().items[1]?.retryOfItemId).toBe(item.id);
});
it('restart after claim pauses without POST and public attempts contain only legacy-safe fields', async () => {
    let creates = 0;
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { creates++; return { externalJobId: 'job', status: 'queued' }; }, get: async () => ({ status: 'unknown' }), download: async () => { throw Error('unexpected'); } };
    const s = await setup(provider);
    s.advance();
    const { applyProviderEvent } = await import('../../domain/src/provider-commands.js');
    await s.store.transact(state => applyProviderEvent(state, state.items[0]!.id, { kind: 'claim', bindingId: provider.bindingId }, { now: s.clock(), manifest: s.fixtures.manifest }));
    await s.store.close();
    const reopened = await GenerationStore.open(join(s.dir, 'state'));
    opened.push(reopened);
    await new GenerationWorker(reopened, provider, s.fixtures, undefined, s.clock).tick();
    expect(creates).toBe(0);
    expect(reopened.read().items[0]?.status).toBe('needs_reconciliation');
    const { projectGenerationSnapshot } = await import('../../domain/src/generation-state.js');
    const attempt = projectGenerationSnapshot(reopened.read()).attempts[0]!;
    expect(Object.keys(attempt).sort()).toEqual(['itemId', 'attemptNo', 'providerBindingId', 'externalIdempotencyKey', 'submissionState', 'createdAt', 'updatedAt'].sort());
    expect(attempt.submissionState).toBe('outcome_unknown');
});
it('poll timeout and restart resume GET only, unknown pauses, reconcile ignores synthetic failure', async () => {
    let creates = 0;
    let polls = 0;
    const ids: string[] = [];
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { creates++; return { externalJobId: 'same-job', status: 'queued' }; }, get: async (id) => {
            ids.push(id);
            polls++;
            if (polls === 1)
                throw Error('secret-timeout');
            return { status: polls === 2 ? 'unknown' : 'failed' };
        }, download: async () => { throw Error('unexpected'); } };
    const s = await setup(provider);
    s.advance();
    await s.worker.tick();
    s.advance();
    await s.worker.tick();
    expect(s.store.read().items[0]?.status).toBe('running');
    const attempt = s.store.read().attempts[0]!;
    expect(Date.parse(attempt.nextPollAt!) - Date.parse(attempt.lastPolledAt!)).toBeGreaterThanOrEqual(100);
    await s.worker.tick();
    expect(polls).toBe(1);
    await s.store.close();
    const reopened = await GenerationStore.open(join(s.dir, 'state'));
    opened.push(reopened);
    const worker = new GenerationWorker(reopened, provider, s.fixtures, undefined, s.clock);
    s.advance();
    await worker.tick();
    expect(reopened.read().items[0]?.status).toBe('needs_reconciliation');
    await worker.tick();
    expect(polls).toBe(2);
    const { reconcileProviderItem } = await import('../../domain/src/provider-commands.js');
    const item = reopened.read().items[0]!;
    const reconciled = await reopened.transact(state => reconcileProviderItem(state, item.id, { expectedVersion: item.version, outcome: 'failure' }, s.clock()));
    expect(reconciled.ok).toBe(true);
    expect(reopened.read().items[0]?.status).toBe('running');
    expect(reopened.read().credits.reserved).toBe(1);
    await worker.tick();
    expect(reopened.read().items[0]?.status).toBe('failed');
    expect(creates).toBe(1);
    expect(ids).toEqual(['same-job', 'same-job', 'same-job']);
});
it('completed without a usable URL stays finalizing and retry-download queries original job', async () => {
    let creates = 0;
    let polls = 0;
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { creates++; return { externalJobId: 'same-job', status: 'queued' }; }, get: async () => { polls++; return { status: 'result_ready' }; }, download: async () => { throw Error('unexpected'); } };
    const s = await setup(provider);
    s.advance();
    await s.worker.tick();
    s.advance();
    await s.worker.tick();
    expect(s.store.read().items[0]?.status).toBe('finalizing');
    expect(s.store.read().credits.reserved).toBe(1);
    const { retryProviderDownload } = await import('../../domain/src/provider-commands.js');
    const item = s.store.read().items[0]!;
    await s.store.transact(state => retryProviderDownload(state, item.id, { expectedVersion: item.version }, s.clock()));
    await s.worker.tick();
    expect(creates).toBe(1);
    expect(polls).toBe(2);
});
it('rejects forged fixture download bytes even with catalog-looking metadata', async () => {
    const fixtures = await FixtureCatalog.open(resolve('apps/web/public/demo'));
    const actual = await fixtures.readFixture('video-5-16x9-720p-silent');
    const provider: GenerationProvider = { bindingId: 'fake-local', create: async () => ({ externalJobId: 'fake-job', status: 'queued' }), get: async () => ({ status: 'result_ready', result: { kind: 'fixture', fixtureKey: 'video-5-16x9-720p-silent' } }), download: async () => ({ kind: 'media', bytes: new Uint8Array([1, 2, 3]), sha256: actual.media.sha256, mime: 'video/mp4', provenance: 'synthetic_provider_simulation', fixtureMedia: actual.media }) };
    const s = await setup(provider, true);
    s.advance();
    await s.worker.tick();
    s.advance();
    await s.worker.tick();
    expect(s.store.read().items[0]?.status).toBe('finalizing');
    expect(s.store.read().credits.reserved).toBe(1);
    expect(s.store.read().mediaMetadata).toHaveLength(0);
});
it.each(['failed', 'cancelled', 'unknown'] as const)('honors confirmed create status %s immediately without polling away evidence', async (status) => {
    let creates = 0;
    let polls = 0;
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { creates++; return { externalJobId: 'confirmed-job', status }; }, get: async () => { polls++; throw Error('timeout'); }, download: async () => { throw Error('unexpected'); } };
    const s = await setup(provider);
    s.advance();
    await s.worker.tick();
    const state = s.store.read();
    expect(state.attempts[0]?.externalJobId).toBe('confirmed-job');
    expect(state.items[0]?.status).toBe(status === 'unknown' ? 'needs_reconciliation' : status);
    expect(state.credits.reserved).toBe(status === 'unknown' ? 1 : 0);
    s.advance();
    await s.worker.tick();
    expect(creates).toBe(1);
    expect(polls).toBe(0);
});
it('persists original claim submittedAt before IO and preserves it after ambiguous response', async () => {
    let entered!: () => void;
    let release!: () => void;
    const arrived = new Promise<void>(r => { entered = r; });
    const gate = new Promise<void>(r => { release = r; });
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { entered(); await gate; throw Error('ambiguous'); }, get: async () => ({ status: 'unknown' }), download: async () => { throw Error('unexpected'); } };
    const s = await setup(provider);
    s.advance();
    const claimedAt = new Date(s.clock()).toISOString();
    const ticking = s.worker.tick();
    await arrived;
    const persisted = s.store.read().attempts[0]?.submittedAt;
    s.advance();
    release();
    await ticking;
    expect(persisted).toBe(claimedAt);
    expect(s.store.read().attempts[0]?.submittedAt).toBe(claimedAt);
    expect(s.store.read().items[0]?.status).toBe('needs_reconciliation');
});
