import { afterEach, expect, it, vi } from 'vitest';
import { mkdir, mkdtemp, readFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { GenerationStore } from './store.js';
import { GenerationApiService } from './service.js';
import { GenerationWorker } from './worker.js';
import { GenerationMediaRepository } from './media-repository.js';
import { FixtureCatalog } from './fixtures.js';
import { AgnesProvider } from './provider/agnes-provider.js';
import { FakeAgnesTransport } from '../tests/helpers/fake-agnes-transport.js';
import { projectGenerationSnapshot } from '../../domain/src/generation-state.js';
import { retryProviderDownload } from '../../domain/src/provider-commands.js';
import { validateProviderAttempt } from '../../domain/src/provider-attempt.js';
const request = { mode: 'video' as const, prompt: 'A simple blue geometric cube on a clean light background, slow gentle camera push-in, minimal studio lighting, stable composition, no text, no people.', count: 1, references: [], video: { durationSeconds: 5, ratio: '16:9' as const, resolution: '720p' as const, audio: false } };
const opened: GenerationStore[] = [];
afterEach(async () => { for (const s of opened.splice(0)) await s.close(); });
it('persists original real facts, exact routing and hash-bound real media across recovery without a second Create', async () => {
  await mkdir(resolve('.cache/provider-media-tests'), { recursive: true });
  const dir = await mkdtemp(resolve('.cache/provider-media-tests/real-worker-'));
  const input = join(dir, 'synthetic.mp4');
  await promisify(execFile)('ffmpeg', ['-v','error','-f','lavfi','-i','color=c=blue:s=1280x704:r=24','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-frames:v','121','-t','5.041667','-c:v','libx264','-threads','1','-pix_fmt','yuv420p','-c:a','aac',input], { windowsHide: true });
  const bytes = await readFile(input);
  const fixtures = await FixtureCatalog.open(resolve('apps/web/public/demo'));
  const store = await GenerationStore.open(join(dir, 'state')); opened.push(store);
  let now = Date.parse('2026-09-13T00:00:00.000Z');
  const service = new GenerationApiService(store, fixtures, () => now);
  expect((await service.create(request, 'one')).ok).toBe(true);
  const url = 'https://platform-outputs.agnes-ai.space/synthetic.mp4?signature=never-store';
  const transport = new FakeAgnesTransport({ apiKey: 'synthetic-test-key', expectedVideoId: 'original-video', mediaUrl: url, mediaBytes: bytes, replies: [
    { operation: 'create', body: { video_id: 'original-video', task_id: 'original-task', id: 'original-id', created_at: 1789257600, status: 'queued', seconds: 5.04, size: '1280x704' } },
    { operation: 'get', body: { video_id: 'changed-video', task_id: 'changed-task', id: 'changed-id', created_at: 1789257700, status: 'completed', seconds: 5.041667, size: '1280x704', metadata: { url, size_mapping: { adjusted: true, width: 1280, height: 704 } } } },
  ] });
  const provider = new AgnesProvider({ apiKey: 'synthetic-test-key', executionKind: 'authorized-real', fetchImpl: transport.fetchImpl });
  const repo = await GenerationMediaRepository.open(join(dir, 'state'), fixtures);
  const worker = new GenerationWorker(store, provider, fixtures, repo, () => now);
  now += 101; await worker.tick();
  expect(store.read().items[0]!.routingSnapshot).toMatchObject({ bindingId: 'agnes-authorized-real', modelKey: 'agnes-video-v2.0' });
  expect(store.read().attempts[0]!.reported).toMatchObject({ videoId: 'original-video', taskId: 'original-task', id: 'original-id', createdAt: 1789257600 });
  const failure = vi.spyOn(repo, 'finalize').mockRejectedValueOnce(Error('synthetic-finalization-failure'));
  now += 101; await worker.tick(); failure.mockRestore();
  let state = store.read();
  expect(state.attempts[0]!.reported).toMatchObject({ videoId: 'original-video', taskId: 'original-task', id: 'original-id', createdAt: 1789257600, status: 'completed', seconds: 5.041667, size: '1280x704' });
  expect(state.attempts[0]!.rawMedia).toMatchObject({ provenance: 'real_provider_output', rawCodec: 'h264', rawActualWidth: 1280, rawActualHeight: 704, rawHasAudio: true, rawFrames: 121, rawDecodeVerified: true });
  const raw = state.attempts[0]!.rawMedia!;
  for (const patch of [{ rawCodec: undefined }, { rawCodec: 'private-tag' }, { provenance: 'synthetic_provider_simulation' }]) expect(() => validateProviderAttempt({ ...state.attempts[0], rawMedia: { ...raw, ...patch } })).toThrow('INVALID_PROVIDER_ATTEMPT');
  await expect(repo.verifyRaw({ ...raw, rawCodec: 'hevc' })).rejects.toThrow('MEDIA_UNAVAILABLE');
  await expect(repo.verifyRaw({ ...raw, rawActualHeight: 720 })).rejects.toThrow('MEDIA_UNAVAILABLE');
  expect(state.items[0]!.status).toBe('finalizing');
  await store.close();
  const reopened = await GenerationStore.open(join(dir, 'state')); opened.push(reopened);
  expect(reopened.read().attempts[0]!.reported).toEqual(state.attempts[0]!.reported);
  const item = reopened.read().items[0]!;
  expect((await reopened.transact(s => retryProviderDownload(s, item.id, { expectedVersion: item.version }, now))).ok).toBe(true);
  await new GenerationWorker(reopened, provider, fixtures, repo, () => now).tick();
  state = reopened.read();
  expect(state.items[0]).toMatchObject({ status: 'succeeded', reviewState: 'pending', libraryState: 'not_saved' });
  expect(state.evaluations).toEqual([]); expect(state.assets).toEqual([]);
  const derived = state.attempts[0]!.derivativeEvidence!;
  expect(derived.media).toMatchObject({ isDemo: false, width: 1280, height: 720, durationMs: 5000, hasAudio: false });
  expect(derived.media).not.toHaveProperty('fixtureKey');
  await expect(reopened.transact(s => { s.items[0]!.routingSnapshot.ruleVersion = 'forged-rule'; return { ok: true, value: true }; })).rejects.toThrow('INVALID_STORE');
  await expect(reopened.transact(s => { s.mediaMetadata[0]!.isDemo = true; return { ok: true, value: true }; })).rejects.toThrow('INVALID_STORE');
  expect(derived.sourceSha256).toBe(state.attempts[0]!.rawMedia!.rawSha256);
  expect((await repo.readMedia(derived.media, derived)).bytes.length).toBe(derived.media.byteSize);
  const forged = { ...derived, media: { ...derived.media, isDemo: true, fixtureKey: 'synthetic-provider-simulation' } };
  await expect(repo.readMedia(forged.media, forged)).rejects.toThrow('MEDIA_UNAVAILABLE');
  expect(JSON.stringify(projectGenerationSnapshot(state))).not.toMatch(/original-task|original-id|rawCodec|sizeMapping|reported|signature=/);
  expect(transport.calls).toEqual(['create', 'get', 'download']); expect(transport.realCalls).toBe(0);
}, 60000);
