import { afterEach, expect, it, vi } from 'vitest';
import { mkdir, mkdtemp } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { GenerationStore } from './store.js';
import { FixtureCatalog } from './fixtures.js';
import { GenerationApiService } from './service.js';
import { GenerationWorker } from './worker.js';
import { type GenerationProvider } from './provider/port.js';
const opened: GenerationStore[] = [];
afterEach(async () => {
    for (const s of opened.splice(0))
        await s.close();
});
async function setup(provider: GenerationProvider, video = false) {
    await mkdir(resolve('.cache/generation-tests'), { recursive: true });
    const dir = await mkdtemp(resolve('.cache/generation-tests/provider-worker-'));
    const store = await GenerationStore.open(join(dir, 'state'));
    opened.push(store);
    const fixtures = await FixtureCatalog.open(resolve('apps/web/public/demo'));
    let now = 1000;
    const service = new GenerationApiService(store, fixtures, () => now);
    await service.create(video ? { mode: 'video', prompt: '真实编排模拟', references: [], count: 1, video: { durationSeconds: 5, ratio: '16:9', resolution: '720p', audio: false } } : { mode: 'copy', prompt: '真实编排模拟', references: [], count: 1, copy: { language: 'zh-CN', maxCharacters: 200 } }, 'new');
    const worker = new GenerationWorker(store, provider, fixtures, undefined, () => now);
    return { dir, store, fixtures, service, worker, advance: () => { now += 101; }, clock: () => now };
}
it('raw is durable before finalization failure and reopened worker finalizes without GET or create', async () => {
    const { GenerationMediaRepository } = await import('./media-repository.js');
    const fixtures = await FixtureCatalog.open(resolve('apps/web/public/demo'));
    const media = await fixtures.readFixture('video-5-16x9-720p-silent');
    let creates = 0;
    let polls = 0;
    let downloads = 0;
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { creates++; return { externalJobId: 'original-job', status: 'queued' }; }, get: async () => { polls++; return { status: 'result_ready', result: { kind: 'https', url: 'https://platform-outputs.agnes-ai.space/synthetic.mp4?signature=never-persist' } }; }, download: async () => { downloads++; return { kind: 'media', bytes: media.bytes, sha256: media.media.sha256, mime: 'video/mp4', provenance: 'synthetic_provider_simulation' }; } };
    const s = await setup(provider, true);
    const repo = await GenerationMediaRepository.open(join(s.dir, 'state'), s.fixtures);
    const worker = new GenerationWorker(s.store, provider, s.fixtures, repo, s.clock);
    const fail = vi.spyOn(repo, 'finalize').mockRejectedValueOnce(Error('secret-postprocess-error'));
    s.advance();
    await worker.tick();
    s.advance();
    await worker.tick();
    const state = s.store.read();
    expect(state.items[0]?.status).toBe('finalizing');
    expect(state.attempts[0]?.rawMedia?.rawSha256).toBe(media.media.sha256);
    expect(state.attempts[0]?.derivativeEvidence).toBeUndefined();
    expect(state.credits.reserved).toBe(1);
    expect(JSON.stringify(state)).not.toMatch(/signature=|secret-postprocess/);
    fail.mockRestore();
    const { retryProviderDownload } = await import('../../domain/src/provider-commands.js');
    const item = state.items[0]!;
    await s.store.transact(st => retryProviderDownload(st, item.id, { expectedVersion: item.version }, s.clock()));
    await s.store.close();
    const reopened = await GenerationStore.open(join(s.dir, 'state'));
    opened.push(reopened);
    const resumed = new GenerationWorker(reopened, provider, s.fixtures, repo, s.clock);
    await resumed.tick();
    expect(reopened.read().items[0]?.status).toBe('succeeded');
    expect(reopened.read().attempts[0]?.derivativeEvidence?.sourceSha256).toBe(media.media.sha256);
    expect(reopened.read().credits).toMatchObject({ reserved: 0, spent: 1 });
    expect({ creates, polls, downloads }).toEqual({ creates: 1, polls: 1, downloads: 1 });
    s.advance();
    await resumed.tick();
    expect({ creates, polls, downloads }).toEqual({ creates: 1, polls: 1, downloads: 1 });
}, 30000);
it.each(['download', 'hash'])('recovers %s failure using the original provider job', async (failure) => {
    const { GenerationMediaRepository } = await import('./media-repository.js');
    const fixtures = await FixtureCatalog.open(resolve('apps/web/public/demo'));
    const actual = await fixtures.readFixture('video-5-16x9-720p-silent');
    let creates = 0;
    let downloads = 0;
    const jobs: string[] = [];
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { creates++; return { externalJobId: 'original-job', status: 'queued' }; }, get: async (id) => { jobs.push(id); return { status: 'result_ready', result: { kind: 'https', url: 'https://platform-outputs.agnes-ai.space/synthetic.mp4' } }; }, download: async () => {
            downloads++;
            if (downloads === 1 && failure === 'download')
                throw Error('secret-download-error');
            return { kind: 'media', bytes: actual.bytes, sha256: downloads === 1 ? '0'.repeat(64) : actual.media.sha256, mime: 'video/mp4', provenance: 'synthetic_provider_simulation' };
        } };
    const s = await setup(provider, true);
    const repository = await GenerationMediaRepository.open(join(s.dir, 'state'), fixtures);
    const worker = new GenerationWorker(s.store, provider, fixtures, repository, s.clock);
    s.advance();
    await worker.tick();
    s.advance();
    await worker.tick();
    const item = s.store.read().items[0]!;
    expect(item.status).toBe('finalizing');
    expect(s.store.read().attempts[0]?.rawMedia).toBeUndefined();
    expect(s.store.read().credits.reserved).toBe(1);
    const { retryProviderDownload } = await import('../../domain/src/provider-commands.js');
    await s.store.transact(state => retryProviderDownload(state, item.id, { expectedVersion: item.version }, s.clock()));
    await worker.tick();
    expect(s.store.read().items[0]?.status).toBe('succeeded');
    expect(creates).toBe(1);
    expect(downloads).toBe(2);
    expect(jobs).toEqual(['original-job', 'original-job']);
}, 30000);
it.each(['result_ready', 'failed'] as const)('retains corrupt raw evidence through unknown/reconcile and recovers %s on the original job', async (terminal) => {
    const { GenerationMediaRepository } = await import('./media-repository.js');
    const { writeFile } = await import('node:fs/promises');
    const fixtures = await FixtureCatalog.open(resolve('apps/web/public/demo'));
    const actual = await fixtures.readFixture('video-5-16x9-720p-silent');
    let creates = 0;
    let polls = 0;
    const jobs: string[] = [];
    const provider: GenerationProvider = { bindingId: 'agnes-simulated', create: async () => { creates++; return { externalJobId: 'raw-job', status: 'queued' }; }, get: async (id) => { jobs.push(id); polls++; return polls === 2 ? { status: 'unknown' } : polls === 3 && terminal === 'failed' ? { status: 'failed' } : { status: 'result_ready', result: { kind: 'https', url: 'https://platform-outputs.agnes-ai.space/synthetic.mp4' } }; }, download: async () => ({ kind: 'media', bytes: actual.bytes, sha256: actual.media.sha256, mime: 'video/mp4', provenance: 'synthetic_provider_simulation' }) };
    const s = await setup(provider, true);
    const repo = await GenerationMediaRepository.open(join(s.dir, 'state'), fixtures);
    const worker = new GenerationWorker(s.store, provider, fixtures, repo, s.clock);
    const finalizer = vi.spyOn(repo, 'finalize').mockRejectedValueOnce(Error('postprocess-failed'));
    s.advance();
    await worker.tick();
    s.advance();
    await worker.tick();
    const before = s.store.read();
    const raw = before.attempts[0]!.rawMedia!;
    await writeFile(join(s.dir, 'state', raw.rawObjectKey), 'corrupt');
    const item = before.items[0]!;
    expect((await s.service.retryDownload(item.id, { expectedVersion: item.version }, 'retry')).ok).toBe(true);
    await worker.tick();
    const unknown = s.store.read();
    expect(unknown.items[0]?.status).toBe('needs_reconciliation');
    expect(unknown.attempts[0]?.rawMedia).toEqual(raw);
    const reconciled = await s.service.reconcile(item.id, { expectedVersion: unknown.items[0]!.version, outcome: 'success' }, 'reconcile');
    expect(reconciled.ok).toBe(true);
    expect(s.store.read().attempts[0]?.rawMedia).toEqual(raw);
    finalizer.mockRestore();
    await worker.tick();
    expect(s.store.read().items[0]?.status).toBe(terminal === 'failed' ? 'failed' : 'succeeded');
    expect(creates).toBe(1);
    expect(jobs).toEqual(['raw-job', 'raw-job', 'raw-job']);
    expect(s.store.read().credits).toMatchObject({ reserved: 0, spent: terminal === 'failed' ? 0 : 1 });
}, 30000);
