const $=id=>document.getElementById(id);
const labels=['商品存在性','商品一致性','人物一致性','结构完整性','动作自然度','时序稳定性','画面清晰度','AI痕迹','指令遵循','参考遵循','营销可用性'];
let token='',selected=null,previewUrl;
async function api(path,options={}){const response=await fetch(path,{...options,headers:{authorization:`Bearer ${token}`,...options.headers}});if(!response.ok){const e=await response.json();throw new Error(e.error);}return response;}
function message(text){$('status').textContent=text;}
async function action(fn){try{await fn();}catch(e){message(e.message);}}
async function mutate(path,data){return (await api(path,{method:'POST',headers:{'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(data)})).json();}
function button(text,fn){const b=document.createElement('button');b.textContent=text;b.addEventListener('click',()=>action(async()=>{b.disabled=true;try{await fn();}finally{b.disabled=false;}}));return b;}
async function download(path){const blob=await(await api(path)).blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='delivery.mp4';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function refresh(){const tasks=(await(await api('/v1/tasks')).json()).tasks;const assets=(await(await api('/v1/assets')).json()).assets;$('tasks').replaceChildren();
 for(const task of tasks){const row=document.createElement('div');row.className='task';const title=document.createElement('strong');title.textContent=task.prompt;row.append(title);const detail=document.createElement('div');detail.className='detail';detail.textContent=`${task.status} / 审核 ${task.reviewState} / 入库 ${task.libraryState} / v${task.version} / 人工导入`;row.append(detail);if(task.derivative && task.status==='ready'){const m=task.derivative.report.result.media;const result=document.createElement('p');result.className='detail';result.textContent=`交付规格 ${m.width}×${m.height} · ${m.frames}帧 · ${m.durationSeconds}秒 · ${m.hasAudio?'含音轨':'无音轨'} · 原始文件保留`;row.append(result);}
 if(task.status!=='processing')row.append(button('后处理为5秒静音720p',async()=>{await mutate(`/v1/tasks/${task.id}/postprocess`,{expectedVersion:task.version,target:{durationSeconds:5,ratio:'16:9',resolution:'720p',audio:false}});await refresh();message('后处理中，可以刷新查看。');}));
 if(task.status==='ready'){row.append(button('观看并审核',async()=>{selected=task;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(await(await api(`/v1/tasks/${task.id}/result`)).blob());$('preview').src=previewUrl;$('review-section').hidden=false;$('review-form').reset();$('review-section').scrollIntoView({behavior:'smooth'});}));row.append(button('下载交付版本',()=>download(`/v1/tasks/${task.id}/result`)));}
 if(task.reviewState==='approved' && task.status==='ready')row.append(button('手动保存到资产库',async()=>{await mutate(`/v1/tasks/${task.id}/assets`,{expectedVersion:task.version});await refresh();}));$('tasks').append(row);}
 $('assets').replaceChildren();for(const asset of assets){const p=document.createElement('p');p.textContent=`${asset.id.slice(0,8)} · ${asset.valid?'审核有效':'审核已失效，禁止作为资产下载'}`;if(asset.valid)p.append(button('下载资产',()=>download(`/v1/assets/${asset.id}/file`)));$('assets').append(p);}message('已同步。');}
$('connect').addEventListener('click',()=>action(async()=>{token=$('token').value.trim()||token;$('token').value='';await refresh();}));
$('import').addEventListener('click',()=>action(async()=>{const file=$('file').files[0];if(!file)throw new Error('请选择 MP4 视频');await api('/v1/tasks/import',{method:'POST',headers:{'content-type':'video/mp4','idempotency-key':crypto.randomUUID(),'x-task-prompt':encodeURIComponent($('prompt').value)},body:file});await refresh();}));
for(let i=0;i<11;i++){const id=`Q${String(i+1).padStart(2,'0')}`;const row=document.createElement('div');row.className='dimension';row.innerHTML=`<strong>${id} ${labels[i]}</strong><label><input id="${id}-app" type="checkbox" checked>适用</label><input id="${id}-reason" placeholder="不适用原因"><label><input id="${id}-issue" type="checkbox">存在问题</label>`;$('dimensions').append(row);}
$('review-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{if(!selected)throw new Error('先选择一个交付版本');const applicability={},issueTags=[];for(let i=0;i<11;i++){const id=`Q${String(i+1).padStart(2,'0')}`;applicability[id]={applicable:$(id+'-app').checked,...(!$(id+'-app').checked?{reason:$(id+'-reason').value}: {})};if($(id+'-issue').checked)issueTags.push(id);}const form={rubricVersion:'rubric-v2-rebuild',score:Number($('score').value),applicability,issueTags,hardFailures:[...document.querySelectorAll('input[name=hard]:checked')].map(el=>el.value),technicalErrors:[],notes:$('notes').value};await mutate(`/v1/tasks/${selected.id}/reviews`,{expectedVersion:selected.version,form,reason:$('reason').value});$('review-section').hidden=true;selected=null;await refresh();});});
